### ISSUE TITLE
Manual item pickup often not triggering

### ISSUE THREAD

**Issue by phryk** [iortcw/iortcw#126]
Heya, I already played through RTCW with this natively on FreeBSD once and absolutely loved it, so thanks for bringing one of my favorite old-school shooters to BSD. :)

I just started an "immersive" run with automatic run, weapon switching and item pickups disabled.

The first two work fine, but the manual pickup (i.e. the hand icon and associated pickup action on the 'use' button) often isn't triggered when it should be. Specifically:

* Weapon shelves (like in the soldiers sleeping dorm in level 1 where the MP40s are) are extremely finicky to trigger
* Items (i.e. weapons) that drop in a way that they clip partway into walls often can't be picked up at all without going into the options and temporarily enabling autopickup

This is on FreeBSD 12.2 (amd64) with iortcw 1.51C from the FreeBSD ports collection.

**Comment by MAN-AT-ARMS** [comment]
This should be fixed in the repository. The fix came in after 1.51c release so maybe it isn't in the ports collection. If you can build from the repository and report back

**Comment by phryk** [comment]
I'm not terribly proficient with binary builds and can't get it to compile – neither manually nor by adapting the port to use the latest commit.

**Comment by MAN-AT-ARMS** [comment]
http://104.194.9.163/iortcw/SP-freebsd-test.tar.gz

Here are replacement game modules for you to try. These .so files go in the 'main' folder

**Comment by MAN-AT-ARMS** [comment]
http://104.194.9.163/iortcw/SP-freebsd-test.zip

Try this build. This is current with repo.

**Comment by phryk** [comment]
Thanks for the build. It expected the `.so` files with `amd64` instead of `x86_64` in the name, but after fixing that I got it to run.
The issue still persists, tho. Might even have gotten worse, as I wasn't able to pick up some guns just lying on the floor.

BTW since I found out how to bind screenshot creation, I can now at least show you the weapon "shelves" I was talking about.

![shot0004](https://user-images.githubusercontent.com/1021513/124956542-60a20580-e018-11eb-98c4-44a8b115374a.jpg)

**Comment by MAN-AT-ARMS** [comment]
What map is this a screenshot of? It's a little dark to tell.

**Comment by phryk** [comment]
Very first map of the singleplayer campaign.
